### ISSUE TITLE
Searching through only current user auctions - bug or feature?

### ISSUE THREAD

**Issue by Prologh** [paweljankowiak06/TAS-serwis-aukcyjny#1]
Searching through auctions shows only auctions authored by currently signed in user.

It seems like a bad design decision, not being able to see other people auctions, especially for an auction site application. 

**Edit:** An even more serious note: how to make bids to other people's auctions when you can't see them? Accessing other people auctions directly by route id works, tested.

**Comment by paweljankowiak06** [comment]
Its feature lol
